name = input('What is your name? ')
print('Please add your marks ')
M = int(input('Maths     : '))
P = int(input('Physics   : '))
C = int(input('Chemistry : '))
E = int(input('English   : '))
p = int(input('P.E       : '))
Total = M + P + C + E + p
Percent = str((Total/500)*100)
print("=======================================")
print('           REPORT CARD')
print('Name: ' +          name)
print('=======================================')
print('Total Marks :' + str(Total) + '/ 500')
print('Percentage  :' +  str(Percent) +  '%')
print('=======================================')
